# Generated by Django 3.1.1 on 2020-11-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product_category', '0001_initial'),
        ('eshop_products', '0002_auto_20201112_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='eshop_product_category.ProductCategory', verbose_name='دسته بندی ها'),
        ),
    ]
