# Generated by Django 3.1.1 on 2020-12-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_product_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_favorite',
        ),
    ]
