# Generated by Django 3.1.1 on 2021-02-24 17:56

from django.db import migrations, models
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0009_auto_20210224_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='200', null=True, upload_to=eshop_products.models.upload_image_path, verbose_name='تصویر', width_field='268'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(height_field='85', upload_to=eshop_products.models.upload_gallery_image_path, verbose_name='تصویر', width_field='85'),
        ),
    ]
