# Generated by Django 3.1.1 on 2021-03-05 19:14

from django.db import migrations, models
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0011_auto_20210224_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to=eshop_products.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
