# Generated by Django 3.1.1 on 2021-03-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0012_auto_20210305_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_comment_open',
            field=models.BooleanField(default=False, verbose_name='باز بودن نظرات'),
        ),
    ]
