# Generated by Django 3.1.1 on 2021-04-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'چت', 'verbose_name_plural': 'چت ها'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
    ]
