# Generated by Django 3.1.1 on 2020-11-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteTitle', models.CharField(max_length=300, verbose_name='عنوان سایت')),
                ('siteAddress', models.CharField(max_length=400, verbose_name='آدرس سایت')),
                ('sitePhone', models.IntegerField(max_length=50, verbose_name='تلفن')),
                ('siteMobile', models.IntegerField(max_length=50, verbose_name='تلفن همراه')),
                ('siteEmail', models.EmailField(max_length=150, verbose_name='ایمیل سایت')),
                ('siteFax', models.CharField(max_length=200, verbose_name='فکس سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'مدیریت تنظیمات',
            },
        ),
    ]
