# Generated by Django 3.1.1 on 2020-11-30 07:25

from django.db import migrations, models
import eshop_settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_sitesetting_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_settings.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
