# Generated by Django 3.1.1 on 2020-12-01 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProductList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_list', models.TextField(verbose_name='لیست علاقه مندی ها')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لیست علاقه مندی ها',
                'verbose_name_plural': 'لیست های علاقه مندی کاربران',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
