# Generated by Django 3.1.1 on 2020-12-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0007_remove_product_is_favorite'),
        ('eshop_favorite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteproductlist',
            name='product_list',
        ),
        migrations.AddField(
            model_name='favoriteproductlist',
            name='product_list',
            field=models.ManyToManyField(to='eshop_products.Product'),
        ),
    ]
