# Generated by Django 3.1.1 on 2020-12-03 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_favorite', '0004_auto_20201203_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteproductlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
