# Generated by Django 3.1.1 on 2021-02-24 17:56

from django.db import migrations, models
import eshop_sliders.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, height_field='445', null=True, upload_to=eshop_sliders.models.upload_image_path, verbose_name='تصویر', width_field='490'),
        ),
    ]
