# Generated by Django 3.1.1 on 2021-02-24 19:39

from django.db import migrations, models
import eshop_sliders.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0004_auto_20210224_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='photo',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eshop_sliders.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
