# Generated by Django 3.1.1 on 2020-12-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='کد پیگیری'),
        ),
    ]
