# Generated by Django 3.1.1 on 2021-03-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0003_auto_20210322_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_address',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='آدرس مشتری'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_fullname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام و نام خانوادگی مشتری'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره مشتری'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_postal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد پستی مشتری'),
        ),
    ]
