# Generated by Django 3.1.1 on 2021-02-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
    ]
