# Generated by Django 3.1.1 on 2021-03-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_comments', '0003_auto_20210206_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
    ]
