# Generated by Django 3.1.1 on 2021-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_comments', '0004_auto_20210311_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تاریخ'),
        ),
    ]
