# Generated by Django 3.1.1 on 2021-04-07 16:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_comments', '0006_auto_20210311_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='عنوان'),
        ),
    ]
